// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypesintegertypes

type GetIntegerInput struct {
	Value *int32
}

func (input GetIntegerInput) Validate() error {
	return nil
}

type GetIntegerOutput struct {
	Value *int32
}

func (input GetIntegerOutput) Validate() error {
	return nil
}

type SimpleIntegerConfig struct {
}

func (input SimpleIntegerConfig) Validate() error {
	return nil
}

type SimpleTypesIntegerBaseException interface {
	// This is a dummy method to allow type assertion since Go empty interfaces
	// aren't useful for type assertion checks. No concrete class is expected to implement
	// this method. This is also not exported.
	interfaceBindingMethod()
}
