// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypessmithystringtypes

type GetStringInput struct {
	Value *string
}

func (input GetStringInput) Validate() error {
	return nil
}

type GetStringOutput struct {
	Value *string
}

func (input GetStringOutput) Validate() error {
	return nil
}

type SimpleStringConfig struct {
}

func (input SimpleStringConfig) Validate() error {
	return nil
}

type SimpleTypesStringBaseException interface {
	// This is a dummy method to allow type assertion since Go empty interfaces
	// aren't useful for type assertion checks. No concrete class is expected to implement
	// this method. This is also not exported.
	interfaceBindingMethod()
}
