// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypessmithystring

import (
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleString/simpletypessmithystringinternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleString/simpletypessmithystringtypes"
	"github.com/dafny-lang/DafnyRuntimeGo/dafny"
)

func GetStringInput_FromDafny(dafnyInput simpletypessmithystringinternaldafnytypes.GetStringInput) simpletypessmithystringtypes.GetStringInput {

	return simpletypessmithystringtypes.GetStringInput{Value: func() *string {
		var s string
		if dafnyInput.Dtor_value().UnwrapOr(nil) == nil {
			return nil
		}
		for i := dafny.Iterate(dafnyInput.Dtor_value().UnwrapOr(nil)); ; {
			val, ok := i()
			if !ok {
				return &[]string{s}[0]
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()}

}

func GetStringOutput_FromDafny(dafnyOutput simpletypessmithystringinternaldafnytypes.GetStringOutput) simpletypessmithystringtypes.GetStringOutput {

	return simpletypessmithystringtypes.GetStringOutput{Value: func() *string {
		var s string
		if dafnyOutput.Dtor_value().UnwrapOr(nil) == nil {
			return nil
		}
		for i := dafny.Iterate(dafnyOutput.Dtor_value().UnwrapOr(nil)); ; {
			val, ok := i()
			if !ok {
				return &[]string{s}[0]
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()}

}

func CollectionOfErrors_Output_FromDafny(dafnyOutput simpletypessmithystringinternaldafnytypes.Error) simpletypessmithystringtypes.CollectionOfErrors {
	listOfErrors := dafnyOutput.Dtor_list()
	message := dafnyOutput.Dtor_message()
	t := simpletypessmithystringtypes.CollectionOfErrors{}
	for i := dafny.Iterate(listOfErrors); ; {
		val, ok := i()
		if !ok {
			break
		}
		err := val.(simpletypessmithystringinternaldafnytypes.Error)
		t.ListOfErrors = append(t.ListOfErrors, Error_FromDafny(err))

	}
	t.Message = func() string {
		var s string
		for i := dafny.Iterate(message); ; {
			val, ok := i()
			if !ok {
				return s
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()
	return t
}
func OpaqueError_Output_FromDafny(dafnyOutput simpletypessmithystringinternaldafnytypes.Error) simpletypessmithystringtypes.OpaqueError {
	return simpletypessmithystringtypes.OpaqueError{
		ErrObject: dafnyOutput.Dtor_obj(),
	}
}

func Error_FromDafny(err simpletypessmithystringinternaldafnytypes.Error) error {
	// Service Errors

	//DependentErrors

	//Unmodelled Errors
	if err.Is_CollectionOfErrors() {
		return CollectionOfErrors_Output_FromDafny(err)
	}

	return OpaqueError_Output_FromDafny(err)
}

func SimpleStringConfig_FromDafny(dafnyOutput simpletypessmithystringinternaldafnytypes.SimpleStringConfig) simpletypessmithystringtypes.SimpleStringConfig {
	return simpletypessmithystringtypes.SimpleStringConfig{}

}
