// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypessmithystringinternaldafnywrapped

import (
	"context"

	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleString/simpletypessmithystring"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleString/simpletypessmithystringinternaldafnytypes"
	"github.com/dafny-lang/DafnyStandardLibGo/Wrappers"
)

type Shim struct {
	simpletypessmithystringinternaldafnytypes.ISimpleTypesStringClient
	client *simpletypessmithystring.Client
}

func WrappedSimpleString(inputConfig simpletypessmithystringinternaldafnytypes.SimpleStringConfig) Wrappers.Result {
	var nativeConfig = simpletypessmithystring.SimpleStringConfig_FromDafny(inputConfig)
	var nativeClient, nativeError = simpletypessmithystring.NewClient(nativeConfig)
	if nativeError != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpletypessmithystringinternaldafnytypes.Companion_Error_.Create_Opaque_(nativeError))
	}
	return Wrappers.Companion_Result_.Create_Success_(&Shim{client: nativeClient})
}

func (shim *Shim) GetString(input simpletypessmithystringinternaldafnytypes.GetStringInput) Wrappers.Result {
	var native_request = simpletypessmithystring.GetStringInput_FromDafny(input)
	var native_response, native_error = shim.client.GetString(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpletypessmithystring.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpletypessmithystring.GetStringOutput_ToDafny(*native_response))
}

func (shim *Shim) GetStringKnownValue(input simpletypessmithystringinternaldafnytypes.GetStringInput) Wrappers.Result {
	var native_request = simpletypessmithystring.GetStringInput_FromDafny(input)
	var native_response, native_error = shim.client.GetStringKnownValue(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpletypessmithystring.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpletypessmithystring.GetStringOutput_ToDafny(*native_response))
}

func (shim *Shim) GetStringUTF8(input simpletypessmithystringinternaldafnytypes.GetStringInput) Wrappers.Result {
	var native_request = simpletypessmithystring.GetStringInput_FromDafny(input)
	var native_response, native_error = shim.client.GetStringUTF8(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpletypessmithystring.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpletypessmithystring.GetStringOutput_ToDafny(*native_response))
}
