// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypesintegerinternaldafnywrapped

import (
	"context"

	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesinteger"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegerinternaldafnytypes"
	"github.com/dafny-lang/DafnyStandardLibGo/Wrappers"
)

type Shim struct {
	simpletypesintegerinternaldafnytypes.ISimpleTypesIntegerClient
	client *simpletypesinteger.Client
}

func WrappedSimpleInteger(inputConfig simpletypesintegerinternaldafnytypes.SimpleIntegerConfig) Wrappers.Result {
	var nativeConfig = simpletypesinteger.SimpleIntegerConfig_FromDafny(inputConfig)
	var nativeClient, nativeError = simpletypesinteger.NewClient(nativeConfig)
	if nativeError != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpletypesintegerinternaldafnytypes.Companion_Error_.Create_Opaque_(nativeError))
	}
	return Wrappers.Companion_Result_.Create_Success_(&Shim{client: nativeClient})
}

func (shim *Shim) GetInteger(input simpletypesintegerinternaldafnytypes.GetIntegerInput) Wrappers.Result {
	var native_request = simpletypesinteger.GetIntegerInput_FromDafny(input)
	var native_response, native_error = shim.client.GetInteger(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpletypesinteger.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpletypesinteger.GetIntegerOutput_ToDafny(*native_response))
}

func (shim *Shim) GetIntegerKnownValueTest(input simpletypesintegerinternaldafnytypes.GetIntegerInput) Wrappers.Result {
	var native_request = simpletypesinteger.GetIntegerInput_FromDafny(input)
	var native_response, native_error = shim.client.GetIntegerKnownValueTest(context.Background(), native_request)
	if native_error != nil {
		return Wrappers.Companion_Result_.Create_Failure_(simpletypesinteger.Error_ToDafny(native_error))
	}
	return Wrappers.Companion_Result_.Create_Success_(simpletypesinteger.GetIntegerOutput_ToDafny(*native_response))
}
