// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypesinteger

import (
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegerinternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegertypes"
	"github.com/dafny-lang/DafnyRuntimeGo/dafny"
)

func GetIntegerInput_FromDafny(dafnyInput simpletypesintegerinternaldafnytypes.GetIntegerInput) simpletypesintegertypes.GetIntegerInput {

	return simpletypesintegertypes.GetIntegerInput{Value: func() *int32 {
		var b int32
		if dafnyInput.Dtor_value().UnwrapOr(nil) == nil {
			return nil
		}
		b = dafnyInput.Dtor_value().UnwrapOr(nil).(int32)
		return &b
	}()}

}

func GetIntegerOutput_FromDafny(dafnyOutput simpletypesintegerinternaldafnytypes.GetIntegerOutput) simpletypesintegertypes.GetIntegerOutput {

	return simpletypesintegertypes.GetIntegerOutput{Value: func() *int32 {
		var b int32
		if dafnyOutput.Dtor_value().UnwrapOr(nil) == nil {
			return nil
		}
		b = dafnyOutput.Dtor_value().UnwrapOr(nil).(int32)
		return &b
	}()}

}

func CollectionOfErrors_Output_FromDafny(dafnyOutput simpletypesintegerinternaldafnytypes.Error) simpletypesintegertypes.CollectionOfErrors {
	listOfErrors := dafnyOutput.Dtor_list()
	message := dafnyOutput.Dtor_message()
	t := simpletypesintegertypes.CollectionOfErrors{}
	for i := dafny.Iterate(listOfErrors); ; {
		val, ok := i()
		if !ok {
			break
		}
		err := val.(simpletypesintegerinternaldafnytypes.Error)
		t.ListOfErrors = append(t.ListOfErrors, Error_FromDafny(err))

	}
	t.Message = func() string {
		var s string
		for i := dafny.Iterate(message); ; {
			val, ok := i()
			if !ok {
				return s
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()
	return t
}
func OpaqueError_Output_FromDafny(dafnyOutput simpletypesintegerinternaldafnytypes.Error) simpletypesintegertypes.OpaqueError {
	return simpletypesintegertypes.OpaqueError{
		ErrObject: dafnyOutput.Dtor_obj(),
	}
}

func Error_FromDafny(err simpletypesintegerinternaldafnytypes.Error) error {
	// Service Errors

	//DependentErrors

	//Unmodelled Errors
	if err.Is_CollectionOfErrors() {
		return CollectionOfErrors_Output_FromDafny(err)
	}

	return OpaqueError_Output_FromDafny(err)
}

func SimpleIntegerConfig_FromDafny(dafnyOutput simpletypesintegerinternaldafnytypes.SimpleIntegerConfig) simpletypesintegertypes.SimpleIntegerConfig {
	return simpletypesintegertypes.SimpleIntegerConfig{}

}
