// Code generated by smithy-go-codegen DO NOT EDIT.

package simpleunion

import (
	"context"

	"github.com/Smithy-dafny/TestModels/Union/simpleunioninternaldafny"
	"github.com/Smithy-dafny/TestModels/Union/simpleunioninternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/Union/simpleuniontypes"
)

type Client struct {
	DafnyClient *simpleunioninternaldafny.SimpleUnionClient
}

func NewClient(clientConfig simpleuniontypes.SimpleUnionConfig) (*Client, error) {
	var dafnyConfig = SimpleUnionConfig_ToDafny(clientConfig)
	var dafny_response = simpleunioninternaldafny.Companion_Default___.SimpleUnion(dafnyConfig)
	if dafny_response.Is_Failure() {
		panic("Client construction failed. This should never happen")
	}
	var dafnyClient = dafny_response.Extract().(*simpleunioninternaldafny.SimpleUnionClient)
	client := &Client{dafnyClient}
	return client, nil
}

func (client *Client) GetUnion(ctx context.Context, params simpleuniontypes.GetUnionInput) (*simpleuniontypes.GetUnionOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := &simpleuniontypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}
	var dafny_request simpleunioninternaldafnytypes.GetUnionInput = GetUnionInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetUnion(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpleunioninternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetUnionOutput_FromDafny(dafny_response.Extract().(simpleunioninternaldafnytypes.GetUnionOutput))
	return &native_response, nil

}

func (client *Client) GetKnownValueUnion(ctx context.Context, params simpleuniontypes.GetKnownValueUnionInput) (*simpleuniontypes.GetKnownValueUnionOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := &simpleuniontypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}
	var dafny_request simpleunioninternaldafnytypes.GetKnownValueUnionInput = GetKnownValueUnionInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetKnownValueUnion(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpleunioninternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetKnownValueUnionOutput_FromDafny(dafny_response.Extract().(simpleunioninternaldafnytypes.GetKnownValueUnionOutput))
	return &native_response, nil

}
