// Code generated by smithy-go-codegen DO NOT EDIT.

package simpleunion

import (
	"github.com/Smithy-dafny/TestModels/Union/simpleunioninternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/Union/simpleuniontypes"
	"github.com/dafny-lang/DafnyRuntimeGo/dafny"
)

func GetUnionInput_FromDafny(dafnyInput simpleunioninternaldafnytypes.GetUnionInput) simpleuniontypes.GetUnionInput {

	return simpleuniontypes.GetUnionInput{Union: func() types.MyUnion {
		var union types.MyUnion
		union = &types.MyUnionMemberIntegerValue{
			Value: dafnyInput.Dtor_union().UnwrapOr(nil).(int32),
		}
		return union
	}()}

}

func GetUnionOutput_FromDafny(dafnyOutput simpleunioninternaldafnytypes.GetUnionOutput) simpleuniontypes.GetUnionOutput {

	return simpleuniontypes.GetUnionOutput{Union: func() types.MyUnion {
		var union types.MyUnion
		union = &types.MyUnionMemberIntegerValue{
			Value: dafnyOutput.Dtor_union().UnwrapOr(nil).(int32),
		}
		return union
	}()}

}

func GetKnownValueUnionInput_FromDafny(dafnyInput simpleunioninternaldafnytypes.GetKnownValueUnionInput) simpleuniontypes.GetKnownValueUnionInput {

	return simpleuniontypes.GetKnownValueUnionInput{Union: func() types.KnownValueUnion {
		var union types.KnownValueUnion
		union = &types.MyUnionMemberIntegerValue{
			Value: dafnyInput.Dtor_union().UnwrapOr(nil).(int32),
		}
		return union
	}()}

}

func GetKnownValueUnionOutput_FromDafny(dafnyOutput simpleunioninternaldafnytypes.GetKnownValueUnionOutput) simpleuniontypes.GetKnownValueUnionOutput {

	return simpleuniontypes.GetKnownValueUnionOutput{Union: func() types.KnownValueUnion {
		var union types.KnownValueUnion
		union = &types.MyUnionMemberIntegerValue{
			Value: dafnyOutput.Dtor_union().UnwrapOr(nil).(int32),
		}
		return union
	}()}

}

func CollectionOfErrors_Output_FromDafny(dafnyOutput simpleunioninternaldafnytypes.Error) simpleuniontypes.CollectionOfErrors {
	listOfErrors := dafnyOutput.Dtor_list()
	message := dafnyOutput.Dtor_message()
	t := simpleuniontypes.CollectionOfErrors{}
	for i := dafny.Iterate(listOfErrors); ; {
		val, ok := i()
		if !ok {
			break
		}
		err := val.(simpleunioninternaldafnytypes.Error)
		t.ListOfErrors = append(t.ListOfErrors, Error_FromDafny(err))

	}
	t.Message = func() string {
		var s string
		for i := dafny.Iterate(message); ; {
			val, ok := i()
			if !ok {
				return s
			} else {
				s = s + string(val.(dafny.Char))
			}
		}
	}()
	return t
}
func OpaqueError_Output_FromDafny(dafnyOutput simpleunioninternaldafnytypes.Error) simpleuniontypes.OpaqueError {
	return simpleuniontypes.OpaqueError{
		ErrObject: dafnyOutput.Dtor_obj(),
	}
}

func Error_FromDafny(err simpleunioninternaldafnytypes.Error) error {
	// Service Errors

	//DependentErrors

	//Unmodelled Errors
	if err.Is_CollectionOfErrors() {
		return CollectionOfErrors_Output_FromDafny(err)
	}

	return OpaqueError_Output_FromDafny(err)
}

func SimpleUnionConfig_FromDafny(dafnyOutput simpleunioninternaldafnytypes.SimpleUnionConfig) simpleuniontypes.SimpleUnionConfig {
	return simpleuniontypes.SimpleUnionConfig{}

}
