// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypesinteger

import (
	"context"

	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegerinternaldafny"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegerinternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegertypes"
)

type Client struct {
	DafnyClient *simpletypesintegerinternaldafny.SimpleIntegerClient
}

func NewClient(clientConfig simpletypesintegertypes.SimpleIntegerConfig) (*Client, error) {
	var dafnyConfig = SimpleIntegerConfig_ToDafny(clientConfig)
	var dafny_response = simpletypesintegerinternaldafny.Companion_Default___.SimpleInteger(dafnyConfig)
	if dafny_response.Is_Failure() {
		panic("Client construction failed. This should never happen")
	}
	var dafnyClient = dafny_response.Extract().(*simpletypesintegerinternaldafny.SimpleIntegerClient)
	client := &Client{dafnyClient}
	return client, nil
}

func (client *Client) GetInteger(ctx context.Context, params simpletypesintegertypes.GetIntegerInput) (*simpletypesintegertypes.GetIntegerOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := &simpletypesintegertypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}
	var dafny_request simpletypesintegerinternaldafnytypes.GetIntegerInput = GetIntegerInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetInteger(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpletypesintegerinternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetIntegerOutput_FromDafny(dafny_response.Extract().(simpletypesintegerinternaldafnytypes.GetIntegerOutput))
	return &native_response, nil

}

func (client *Client) GetIntegerKnownValueTest(ctx context.Context, params simpletypesintegertypes.GetIntegerInput) (*simpletypesintegertypes.GetIntegerOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := &simpletypesintegertypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}
	var dafny_request simpletypesintegerinternaldafnytypes.GetIntegerInput = GetIntegerInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetIntegerKnownValueTest(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpletypesintegerinternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetIntegerOutput_FromDafny(dafny_response.Extract().(simpletypesintegerinternaldafnytypes.GetIntegerOutput))
	return &native_response, nil

}
