// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypesinteger

import (
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegerinternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleInteger/simpletypesintegertypes"
	"github.com/dafny-lang/DafnyRuntimeGo/dafny"
	"github.com/dafny-lang/DafnyStandardLibGo/Wrappers"
)

func GetIntegerInput_ToDafny(nativeInput simpletypesintegertypes.GetIntegerInput) simpletypesintegerinternaldafnytypes.GetIntegerInput {

	return func() simpletypesintegerinternaldafnytypes.GetIntegerInput {

		return simpletypesintegerinternaldafnytypes.Companion_GetIntegerInput_.Create_GetIntegerInput_(func() Wrappers.Option {
			if nativeInput.Value == nil {
				return Wrappers.Companion_Option_.Create_None_()
			}
			return Wrappers.Companion_Option_.Create_Some_(*nativeInput.Value)
		}())
	}()

}

func GetIntegerOutput_ToDafny(nativeOutput simpletypesintegertypes.GetIntegerOutput) simpletypesintegerinternaldafnytypes.GetIntegerOutput {

	return func() simpletypesintegerinternaldafnytypes.GetIntegerOutput {

		return simpletypesintegerinternaldafnytypes.Companion_GetIntegerOutput_.Create_GetIntegerOutput_(func() Wrappers.Option {
			if nativeOutput.Value == nil {
				return Wrappers.Companion_Option_.Create_None_()
			}
			return Wrappers.Companion_Option_.Create_Some_(*nativeOutput.Value)
		}())
	}()

}

func CollectionOfErrors_Input_ToDafny(nativeInput simpletypesintegertypes.CollectionOfErrors) simpletypesintegerinternaldafnytypes.Error {
	var e []interface{}
	for _, i2 := range nativeInput.ListOfErrors {
		e = append(e, Error_ToDafny(i2))
	}
	return simpletypesintegerinternaldafnytypes.Companion_Error_.Create_CollectionOfErrors_(dafny.SeqOf(e...), dafny.SeqOfChars([]dafny.Char(nativeInput.Message)...))
}
func OpaqueError_Input_ToDafny(nativeInput simpletypesintegertypes.OpaqueError) simpletypesintegerinternaldafnytypes.Error {
	return simpletypesintegerinternaldafnytypes.Companion_Error_.Create_Opaque_(nativeInput.ErrObject)
}

func Error_ToDafny(err error) simpletypesintegerinternaldafnytypes.Error {
	switch err.(type) {
	// Service Errors

	//DependentErrors

	//Unmodelled Errors
	case simpletypesintegertypes.CollectionOfErrors:
		return CollectionOfErrors_Input_ToDafny(err.(simpletypesintegertypes.CollectionOfErrors))

	default:
		// TODO: Is changing from the commented code to this new one reasonable?
		// return OpaqueError_Input_ToDafny(err.(*simpleconstraintstypes.OpaqueError))

		// TODO: why is err a pointer?
		error, ok := err.(*simpletypesintegertypes.OpaqueError)

		if !ok {
			panic("Error is not an OpaqueError")
		}
		if error == nil {
			panic("Error is nil")
		}
		return OpaqueError_Input_ToDafny(*error)
	}
}

func SimpleIntegerConfig_ToDafny(nativeInput simpletypesintegertypes.SimpleIntegerConfig) simpletypesintegerinternaldafnytypes.SimpleIntegerConfig {
	return func() simpletypesintegerinternaldafnytypes.SimpleIntegerConfig {

		return simpletypesintegerinternaldafnytypes.Companion_SimpleIntegerConfig_.Create_SimpleIntegerConfig_()
	}()

}
