// Code generated by smithy-go-codegen DO NOT EDIT.

package simpletypessmithystring

import (
	"context"

	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleString/simpletypessmithystringinternaldafny"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleString/simpletypessmithystringinternaldafnytypes"
	"github.com/Smithy-dafny/TestModels/SimpleTypes/SimpleString/simpletypessmithystringtypes"
)

type Client struct {
	DafnyClient *simpletypessmithystringinternaldafny.SimpleStringClient
}

func NewClient(clientConfig simpletypessmithystringtypes.SimpleStringConfig) (*Client, error) {
	var dafnyConfig = SimpleStringConfig_ToDafny(clientConfig)
	var dafny_response = simpletypessmithystringinternaldafny.Companion_Default___.SimpleString(dafnyConfig)
	if dafny_response.Is_Failure() {
		panic("Client construction failed. This should never happen")
	}
	var dafnyClient = dafny_response.Extract().(*simpletypessmithystringinternaldafny.SimpleStringClient)
	client := &Client{dafnyClient}
	return client, nil
}

func (client *Client) GetString(ctx context.Context, params simpletypessmithystringtypes.GetStringInput) (*simpletypessmithystringtypes.GetStringOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := &simpletypessmithystringtypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}
	var dafny_request simpletypessmithystringinternaldafnytypes.GetStringInput = GetStringInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetString(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpletypessmithystringinternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetStringOutput_FromDafny(dafny_response.Extract().(simpletypessmithystringinternaldafnytypes.GetStringOutput))
	return &native_response, nil

}

func (client *Client) GetStringKnownValue(ctx context.Context, params simpletypessmithystringtypes.GetStringInput) (*simpletypessmithystringtypes.GetStringOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := &simpletypessmithystringtypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}
	var dafny_request simpletypessmithystringinternaldafnytypes.GetStringInput = GetStringInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetStringKnownValue(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpletypessmithystringinternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetStringOutput_FromDafny(dafny_response.Extract().(simpletypessmithystringinternaldafnytypes.GetStringOutput))
	return &native_response, nil

}

func (client *Client) GetStringUTF8(ctx context.Context, params simpletypessmithystringtypes.GetStringInput) (*simpletypessmithystringtypes.GetStringOutput, error) {
	err := params.Validate()
	if err != nil {
		opaqueErr := &simpletypessmithystringtypes.OpaqueError{
			ErrObject: err,
		}
		return nil, opaqueErr
	}
	var dafny_request simpletypessmithystringinternaldafnytypes.GetStringInput = GetStringInput_ToDafny(params)
	var dafny_response = client.DafnyClient.GetStringUTF8(dafny_request)

	if dafny_response.Is_Failure() {
		err := dafny_response.Dtor_error().(simpletypessmithystringinternaldafnytypes.Error)
		return nil, Error_FromDafny(err)
	}
	var native_response = GetStringOutput_FromDafny(dafny_response.Extract().(simpletypessmithystringinternaldafnytypes.GetStringOutput))
	return &native_response, nil

}
