name: Library Go tests

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  test_go:
    strategy:
      fail-fast: false
      matrix:
        library: [
          # TestModels/dafny-dependencies/StandardLibrary, # This stores current Polymorph dependencies that all TestModels depend on
          TestModels/Aggregate,
          # TestModels/AggregateReferences,
          TestModels/CodegenPatches,
          TestModels/Constraints,
          TestModels/Constructor,
          # TestModels/Dependencies,
          TestModels/Errors,
          TestModels/Extendable,
          TestModels/Extern,
          # TestModels/LanguageSpecificLogic,
          # TestModels/LocalService,
          # TestModels/MultipleModels,
          TestModels/Refinement,
          TestModels/Resource,
          # TestModels/SimpleTypes/BigDecimal,
          # TestModels/SimpleTypes/BigInteger,
          TestModels/SimpleTypes/SimpleBlob,
          TestModels/SimpleTypes/SimpleBoolean,
          # TestModels/SimpleTypes/SimpleByte,
          TestModels/SimpleTypes/SimpleDouble,
          TestModels/SimpleTypes/SimpleEnum,
          # TestModels/SimpleTypes/SimpleEnumV2,
          # TestModels/SimpleTypes/SimpleFloat,
          TestModels/SimpleTypes/SimpleInteger,
          TestModels/SimpleTypes/SimpleLong,
          # TestModels/SimpleTypes/SimpleShort,
          TestModels/SimpleTypes/SimpleString,
          # TestModels/SimpleTypes/SimpleTimestamp,
          # TestModels/Union,
          # TestModels/aws-sdks/ddb,
          # TestModels/aws-sdks/kms
        ]
    runs-on: "macos-12"
    steps:
      - uses: actions/checkout@v2

      # - name: Setup Dafny 4.5.0
      #   uses: dafny-lang/setup-dafny-action@v1.7.0
      #   with:
      #     dafny-version: 4.5.0
      # TODO: Setup Dafny once its released
      - name: Install Dafny dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0 mono-complete z3

      - name: Build Dafny from source
        run: |
          git clone https://github.com/dafny-lang/dafny.git --recurse-submodules
          cd dafny
          make exe
      
      - name: Install Z3 version 4.12.1
        run: |
          cd $GITHUB_WORKSPACE/dafny
          make z3-ubuntu

      - name: Add Dafny to PATH
        run: |
          echo "$GITHUB_WORKSPACE/dafny/Scripts" >> $GITHUB_PATH

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install Go imports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: polymorph dafny dependencies
        shell: bash
        working-directory: ./TestModels/dafny-dependencies/StandardLibrary
        run: |
          make polymorph_dafny
          make transpile_go
          make polymorph_go 

      - name: Generate Polymorph Dafny and Go code
        shell: bash
        working-directory: ./${{ matrix.library }}
        run: |
          make polymorph_dafny
          sh ./removeDotFromExtern.sh
          make transpile_go
          make polymorph_go

          if [ "${{ matrix.library }}" == "TestModels/Extern" ]; then
            rm -rf ./runtimes/go/ImplementationFromDafny-go/src/ExternConstructor
            rm -rf ./runtimes/go/ImplementationFromDafny-go/src/SimpleExternImpl
            rm -rf ./runtimes/go/TestsFromDafny-go/src/ExternConstructor
            rm -rf ./runtimes/go/TestsFromDafny-go/src/SimpleExternImpl
          fi

          if [ "${{ matrix.library }}" == "TestModels/Extendable" ]; then
            rm -rf runtimes/go/TestsFromDafny-go/src/simpleextendableresourcesinternaldafnynativeresourcefactory
            rm -rf runtimes/go/ImplementationFromDafny-go/src/simpleextendableresourcesinternaldafnynativeresourcefactory
          fi

          export GOPATH=$(pwd)/runtimes/go/ImplementationFromDafny-go:$GITHUB_WORKSPACE/TestModels/dafny-dependencies/StandardLibrary/runtimes/go/ImplementationFromDafny-go:$(pwd)/runtimes/go/TestsFromDafny-go:$GITHUB_WORKSPACE/DafnyRuntimeGo/:$(pwd)/runtimes/go/ManualChanges
          goimports -w runtimes/go/
          cd runtimes/go/TestsFromDafny-go/
          go run TestsFromDafny.go