name: Library Go tests

on:
  pull_request:
  push:
    branches:
    # TODO: Change to main branch
      - rishav-go-CI

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Install Dafny dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0 mono-complete z3

      - name: Build Dafny from source
        run: |
          git clone https://github.com/dafny-lang/dafny.git --recurse-submodules
          cd dafny
          make exe
      
      - name: Install Z3 version 4.12.1
        run: |
          cd $GITHUB_WORKSPACE/dafny
          make z3-ubuntu

      - name: Add Dafny to PATH
        run: |
          echo "$GITHUB_WORKSPACE/dafny/Scripts" >> $GITHUB_PATH

      - name: Check Dafny installation
        run: |
          dafny --version