name: Library Go tests

on:
  pull_request:
  push:
    branches:
    # TODO: Change to main branch
      - rishav-go-CI

jobs:
  test_go:
    strategy:
      fail-fast: false
      matrix:
        library: [
          # TestModels/dafny-dependencies/StandardLibrary, # This stores current Polymorph dependencies that all TestModels depend on
          # TestModels/Aggregate,
          # TestModels/AggregateReferences,
          # TestModels/CodegenPatches,
          # TestModels/Constraints,
          # TestModels/Constructor,
          # TestModels/Dependencies,
          # TestModels/Errors,
          # TestModels/Extendable,
          # TestModels/Extern,
          # TestModels/LanguageSpecificLogic,
          # TestModels/LocalService,
          # TestModels/MultipleModels,
          # TestModels/Refinement,
          # TestModels/Resource,
          # TestModels/SimpleTypes/BigDecimal,
          # TestModels/SimpleTypes/BigInteger,
          # TestModels/SimpleTypes/SimpleBlob,
          # TestModels/SimpleTypes/SimpleBoolean,
          # TestModels/SimpleTypes/SimpleByte,
          # TestModels/SimpleTypes/SimpleDouble,
          # TestModels/SimpleTypes/SimpleEnum,
          # TestModels/SimpleTypes/SimpleEnumV2,
          # TestModels/SimpleTypes/SimpleFloat,
          # TestModels/SimpleTypes/SimpleInteger,
          # TestModels/SimpleTypes/SimpleLong,
          # TestModels/SimpleTypes/SimpleShort,
          TestModels/SimpleTypes/SimpleString,
          # TestModels/SimpleTypes/SimpleTimestamp,
          # TestModels/Union,
          # TestModels/aws-sdks/ddb,
          # TestModels/aws-sdks/kms,
        ]
    runs-on: "macos-12"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dafny 4.5.0
        uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: 4.5.0

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Install Go imports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Generate Polymorph Dafny and Go code
        shell: bash
        working-directory: ./${{ matrix.library }}
        run: |
          make polymorph_dafny
          sh ./removeDotFromExtern.sh
          make transpile_go
          make polymorph_go
          export GOPATH=$(pwd)/runtimes/go/ImplementationFromDafny-go:$GITHUB_WORKSPACE/TestModels/dafny-dependencies/StandardLibrary/runtimes/go/ImplementationFromDafny-go:$(pwd)/runtimes/go/TestsFromDafny-go:$GITHUB_WORKSPACE/DafnyRuntimeGo/
          goimports -w runtimes/go/
          ls $GITHUB_WORKSPACE/TestModels/dafny-dependencies/StandardLibrary/runtimes/go/ImplementationFromDafny-go/Wrappers
          GO111MODULE=auto go run runtimes/go/TestsFromDafny-go/src/TestsFromDafny.go